name: service-paths
recipe: drupal10

config:
  php: '8.1'
  via: nginx
  composer_version: 2-latest
  webroot: web
  database: mariadb:10.3
  xdebug: off
  config:
    php: .lando/php.ini

tooling:
  grumphp:
    description: Runs grumphp commands
    cmd:
      - appserver: ./vendor/bin/grumphp
  import:
    description: Import the services data
    cmd:
      - appserver: /app/.lando/import.sh
  npm:
    description: Runs npm commands
    service: node
  psalm:
    description: Run Psalm tasks
    cmd:
      - appserver: ./vendor/bin/psalm
  syncdb:
    description: Synchronizes local db with test env
    cmd:
      - appserver: /app/.lando/syncdb.sh
  update:
    description: Updates local db & enables dev components
    cmd:
      - appserver: /app/.lando/update.sh
  xdebug:
    description: Loads Xdebug in the selected mode
    cmd:
      - appserver: /app/.lando/xdebug.sh
    user: root

services:
  appserver:
    build:
      - composer install
    overrides:
      environment:
        HASH_SALT: notsosecurehash
        ENVIRONMENT_NAME: local
        DB_NAME_DRUPAL: drupal10
        DB_USER_DRUPAL: drupal10
        DB_PASS_DRUPAL: drupal10
        DB_HOST_DRUPAL: database
        DRUSH_OPTIONS_URI: https://service-paths.lndo.site
        # Support debugging with XDEBUG 3.
        XDEBUG_MODE:
        # Support debugging Drush with XDEBUG 3.
        PHP_IDE_CONFIG: "serverName=appserver"
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
  node:
    type: node:16
    build:
      - npm install
      - cd ./web/themes/custom/service-paths-theme && npm install
      - cd ./web/themes/custom/service-paths-theme && npm run build && npm run build-storybook
  storybook:
    type: 'php:8.1'
    webroot: web/themes/custom/service-paths-theme/storybook-static
    ssl: true

proxy:
  mailhog:
    - mail-service-paths.lndo.site
  storybook:
    - storybook.lndo.site

version: v3.20.8
