version: 2.1

orbs:
  silta: silta/silta@0.1

executors:
  cicd73:
    docker:
      - image: eu.gcr.io/silta-images/cicd:circleci-php7.3-node12-composer1-v0.1

workflows:
  version: 2
  commit:
    jobs:
      # - silta/drupal-validate:
      #     name: validate
      #     executor: cicd73
      #     post-validation:
      #       - run: echo "You can add additional validation here!"

      # - silta/analyze:
      #     name: analyze
      #     context: analyze
      #     sources: web

      - silta/drupal-build-deploy: &build-deploy
          name: build-deploy
          executor: cicd73
          codebase-build:
            - silta/drupal-composer-install
            - silta/npm-install-build:
                path: './web/themes/custom/service-paths-theme'
          silta_config: silta/silta.yml,silta/silta-dev.yml
          context: silta_dev
          # requires:
          #   - analyze
          #   - validate
          filters:
            branches:
              only:
                - master

      - silta/drupal-build-deploy:
          # Extend the build-deploy configuration for the production environment.
          <<: *build-deploy
          name: build-deploy-prod
          silta_config: silta/silta.yml,silta/silta-prod.yml
          context: silta_finland
          filters:
            branches:
              only: production

      # Storybook deployment to development cluster.
      - silta/simple-build-deploy:
          name: build-storybook
          # requires:
          #   - validate
          context: silta_dev
          codebase_root: web/themes/custom/service-paths-theme
          build_folder: storybook-static
          codebase-build:
            - silta/npm-install-build:
                build-command: npm run build && npm run build-storybook
          filters:
            branches:
              ignore: production
