version: 2.1

orbs:
  silta: silta/silta@0.1

jobs:
  pushcode:
    docker:
      - image: wunderio/silta-cicd:v0.1
    steps:
      - add_ssh_keys:
          fingerprints:
            - "52:0a:3b:ed:41:4b:b3:78:0d:15:21:a3:84:89:48:1f"
      - checkout
      - run: ls -al
      - run: git status
      - run: git remote add turkugithub git@github.com:City-of-Turku/palvelupolut
      - run: git config --global user.email "reposync@wunder.io"
      - run: git config --global user.name "Repository Sync Robot"
      - run: git checkout ${CIRCLE_BRANCH}
      - run: ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - run: git push -u turkugithub ${CIRCLE_BRANCH} -f

executors:
  cicd81:
    docker:
      - image: wunderio/silta-cicd:circleci-php8.1-node16-composer2

workflows:
  version: 2
  commit:
    jobs:
      - silta/drupal-validate:
          name: validate
          executor: cicd81

      - silta/analyze:
          name: analyze
          context: analyze
          sources: web

      - silta/drupal-build-deploy: &build-deploy
          name: build-deploy
          executor: cicd81
          codebase-build:
            - silta/drupal-composer-install
            - silta/npm-install-build:
                path: './web/themes/custom/service-paths-theme'
          silta_config: silta/silta.yml,silta/silta-dev.yml
          context: silta_dev
          requires:
            - analyze
            - validate
          filters:
            branches:
              ignore:
                - production
                - /dependabot\/.*/

      # Drupal deployment to production cluster.
      - silta/drupal-build-deploy:
          # Extend the build-deploy configuration for the production environment.
          <<: *build-deploy
          name: build-deploy-prod
          silta_config: silta/silta.yml,silta/silta-prod.yml,silta/secrets_prod
          decrypt_files: silta/secrets_prod
          context: silta_finland
          filters:
            branches:
              only: production

      # Storybook deployment to development cluster.
      - silta/simple-build-deploy:
          name: build-storybook
          executor: cicd81
          context: silta_dev
          codebase_root: web/themes/custom/service-paths-theme
          build_folder: storybook-static
          release-suffix: sb
          codebase-build:
            - silta/npm-install-build:
                build-command: npm run build && npm run build-storybook
          filters:
            branches:
              ignore:
                - production
                - /dependabot\/.*/

      # Storybook deployment to production cluster.
      - silta/simple-build-deploy:
          name: build-storybook-prod
          executor: cicd81
          context: silta_finland
          codebase_root: web/themes/custom/service-paths-theme
          build_folder: storybook-static
          release-suffix: sb
          codebase-build:
            - silta/decrypt-files:
                files: silta/secrets_prod
                secret_key_env: SECRET_KEY
            - silta/npm-install-build:
                build-command: npm run build && npm run build-storybook
          silta_config: silta/silta.yml,silta/silta-storybook-prod.yml,silta/secrets_prod
          filters:
            branches:
              only: production

      # Push code from master branch to Turku Github repository.
      - pushcode:
          name: pushcode
          context: silta_finland
          requires:
            - build-deploy
          filters:
            branches:
              only:
                - master

# VS Code Extension Version: 1.5.1
