_core:
  default_config_hash: LqXuXXQCTd1NWw7dGLef0PCi3_aEEWQuogAblo4hHaE
hotlink: true
origin: 'https://palvelupolut.fi'
origin_dir: sites/default/files
use_imagecache_root: true
proxy_headers: ''
verify: true
excluded_extensions: ''
