root: true
extends:
  - airbnb
  - plugin:prettier/recommended
plugins:
  - react
env:
  es6: true
  browser: true
globals:
  Drupal: true
parser: babel-eslint
rules:
  strict: 0
  no-param-reassign: 0
  react/jsx-filename-extension: [1, { 'extensions': ['.js', '.jsx'] }]
  react/jsx-props-no-spreading: 0
  import/no-extraneous-dependencies: 0
  react/prefer-stateless-function: 0
  jsx-a11y/label-has-for:
    - 2
    - required:
        some:
          - nesting
          - id
overrides:
  - files:
      - '*.stories.js'
    rules:
      react/no-danger: 0
