
@startuml Service path
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4.puml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Context.puml
' !include https://raw.githubusercontent.com/adrianvlupu/latest/C4_Container.puml
' !include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Component.puml
' !include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Dynamic.puml
' !include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Deployment.puml
' uncomment the following line and comment the first to use locally
' !include C4_Component.puml
' https://github.com/adrianvlupu/C4-PlantUML

' !include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Container.puml

!define ICONURL https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v2.4.0
!includeurl ICONURL/common.puml
!includeurl ICONURL/devicons/mysql.puml
!includeurl ICONURL/devicons2/apache.puml
!includeurl ICONURL/font-awesome/server.puml
!includeurl ICONURL/font-awesome-5/drupal.puml

' !define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
' !define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
' !include DEVICONS/angular.puml
' !include DEVICONS/java.puml
' !include DEVICONS/msql_server.puml
' !include FONTAWESOME/users.puml
' !include FONTAWESOME/font-awesome-5/drupal.puml


LAYOUT_WITH_LEGEND()

' LAYOUT_AS_SKETCH()
title Service path system

Person(user, 'User')
System(sp, "Service Path System", "")
System(ptv, "PTV", "PTV API", "")
' Container(ma, "Mautic", "Open sourced Marketing Automation", "", "")

Rel(ptv, sp, "json")
Rel(user, sp, "consuming content")
' BiRel(ma, cdp, "REST API")
' BiRel(ma, cms, "Talks")
' Rel(unomi, cms, "")
' Rel(spa, api, "Uses", "https")
' Rel_R(api, db, "Reads/Writes")
@enduml
